# Use an official Node runtime as the base image
FROM node:16

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY ../../package*.json ./

# Install NestJS CLI and dependencies
# RUN npm i -g @nestjs/cli 
RUN npm install

# Bundle app source
COPY ../../ .

# Default port exposure
EXPOSE 3000

# Start the app with hot-reloading enabled
CMD ["npm", "run", "start:dev", "product"]
